/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MainPage;

import Connection.DBUtils;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author nguye
 */
public class DangNhapForm extends javax.swing.JFrame {

    /**
     * Creates new form DangNhapForm
     */
    Border panel_Border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.yellow);
    public DangNhapForm() {
        initComponents();
        setSize(900,500);
        //center the form
        this.setLocationRelativeTo(null);
        //set border
        //jPanel_Container.setBorder(panel_Border);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLayout(null);
        //setTitle(".:JRadioButton:.");
        setVisible(true);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        check = new javax.swing.JCheckBox();
        btnDangNhap = new javax.swing.JButton();
        btnDangKi = new javax.swing.JButton();
        cbShowPass = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("ĐĂNG NHẬP");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(430, 90, 260, 54);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("TÊN ĐĂNG NHẬP");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 240, 130, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("MẬT KHẨU");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 290, 90, 30);

        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUserName);
        txtUserName.setBounds(300, 240, 200, 25);
        getContentPane().add(txtPassword);
        txtPassword.setBounds(300, 290, 200, 25);

        check.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        check.setText("Nhớ mật khẩu");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });
        getContentPane().add(check);
        check.setBounds(250, 350, 200, 24);

        btnDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/login.png"))); // NOI18N
        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.setAlignmentY(0.2F);
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        getContentPane().add(btnDangNhap);
        btnDangNhap.setBounds(130, 420, 140, 45);

        btnDangKi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/signup.png"))); // NOI18N
        btnDangKi.setText("Đăng kí");
        btnDangKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKiActionPerformed(evt);
            }
        });
        getContentPane().add(btnDangKi);
        btnDangKi.setBounds(380, 420, 140, 45);

        cbShowPass.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/image/eye-16.jpg"))); // NOI18N
        cbShowPass.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/eye-16.jpg"))); // NOI18N
        cbShowPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/eye-16.jpg"))); // NOI18N
        cbShowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbShowPassActionPerformed(evt);
            }
        });
        getContentPane().add(cbShowPass);
        cbShowPass.setBounds(510, 295, 30, 20);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/xoa.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(880, 0, 20, 20);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/arrow-92-24.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(0, 0, 30, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dangnhap.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:
        String username = txtUserName.getText();
        String password = new String(txtPassword.getPassword());
        StringBuilder bd = new StringBuilder();
        if(username.equals("")||password.equals(""))
            JOptionPane.showMessageDialog(null,"Tài Khoản không được để trống","Trống",JOptionPane.WARNING_MESSAGE);
        /*Tài khoản admin*/
        else{
        if(password.equals("admin")&&username.equals("admin")){
            JOptionPane.showMessageDialog(null,"Đăng nhập với tài khoản Admin!");
            //hide();
            AdminPage ad =new AdminPage();
            AdminPage.main(null);}
        else{
            try{
                Connection con = null;
                con = new DBUtils().createConn();
              
                String SQL ="SELECT TenDN, MK FROM KHACHHANG\n"
                        + "WHERE TenDN=? and MK=?";
                PreparedStatement ps=con.prepareStatement(SQL);
                ps.setString(1, username);
                ps.setString(2,password);
                ResultSet rs = ps.executeQuery();
                if(rs.next())
                {
                    JOptionPane.showMessageDialog(this,"Đăng nhập thành công!");
                    hide();
                    CustomerPage cp = new CustomerPage(txtUserName.getText());
                    CustomerPage.main(null);
                
                    }
                else
                {
                    JOptionPane.showMessageDialog(this,"Tài khoản hoặc mật khẩu sai","Sai mật khẩu!",JOptionPane.ERROR_MESSAGE);
                }
            }catch (HeadlessException | SQLException ex)
            {
               System.out.println(ex);
            } 
        }}
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void btnDangKiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKiActionPerformed
        // TODO add your handling code here:
        DangKi dk =new DangKi();
        DangKi.main(null);
    }//GEN-LAST:event_btnDangKiActionPerformed

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkActionPerformed

    private void cbShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbShowPassActionPerformed
        // TODO add your handling code here:
        if(cbShowPass.isSelected())
        {
            txtPassword.setEchoChar((char)0);
        }
        else{
            txtPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_cbShowPassActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        mainpage.main(null);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhapForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhapForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhapForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhapForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhapForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKi;
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JCheckBox cbShowPass;
    private javax.swing.JCheckBox check;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
