/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MainPage;

import Connection.DBUtils;
import javax.swing.JOptionPane;

/**
 *
 * @author nguye
 */
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

public class DangKi extends javax.swing.JFrame {

    /**
     * Creates new form DangKy
     */
    Border panel_Border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.yellow);
    
    public DangKi() {
        initComponents();
        setSize(900,500);
        //center the form
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLayout(null);
        setVisible(true);
        setResizable(false);
        cbbGT.setModel(new DefaultComboBoxModel<>(new String[]{"Nam", "Nữ"}));
    }
    public String LayMaKH(){
        String MaKH = "";
        Connection con = new DBUtils().createConn();
        String StrSQL = "SELECT MAKH FROM KHACHHANG order by MAKH DESC";
        try{
            Statement stat = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,
                                  ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = stat.executeQuery(StrSQL);
            if (rs.absolute(1)==false){
                MaKH="KH0001";
            }
            else {
                String MaKHHienTai = rs.getString("MaKH");
                MaKH = MaKHHienTai.substring(2,6);
                int MaKHmoi = Integer.parseInt(MaKH) +1;
                if(MaKHmoi<10)
                    MaKH = "KH000"+MaKHmoi;
                else
                    if(MaKHmoi<100)
                        MaKH = "KH00"+MaKHmoi;
                    else
                        if(MaKHmoi<1000)
                            MaKH = "KH0"+MaKHmoi;
                        else
                            MaKH = "KH"+MaKHmoi;
            }
            con.close();
        } catch (Exception e){
            e.printStackTrace();
            System.out.println("Lỗi");
        }
        return MaKH;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        dtcNgSinh = new com.toedter.calendar.JDateChooser();
        cbbGT = new javax.swing.JComboBox<>();
        txtUserName = new javax.swing.JTextField();
        btnDN = new javax.swing.JButton();
        btnDK = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("ĐĂNG KÍ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(400, 30, 210, 60);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("TÊN ĐĂNG NHẬP");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(410, 340, 150, 25);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("MẬT KHẨU");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(410, 380, 100, 25);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("HỌ VÀ TÊN");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(410, 140, 100, 25);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("NGÀY SINH");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(410, 260, 150, 25);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("GIỚI TÍNH");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(410, 300, 100, 25);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("EMAIL");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(410, 180, 100, 25);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("SỐ ĐIỆN THOẠI");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(410, 220, 150, 25);
        getContentPane().add(txtTenKH);
        txtTenKH.setBounds(610, 140, 200, 25);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(610, 180, 200, 25);
        getContentPane().add(txtSDT);
        txtSDT.setBounds(610, 220, 200, 25);
        getContentPane().add(dtcNgSinh);
        dtcNgSinh.setBounds(610, 260, 200, 25);

        cbbGT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbbGT);
        cbbGT.setBounds(610, 300, 100, 25);
        getContentPane().add(txtUserName);
        txtUserName.setBounds(610, 340, 200, 25);

        btnDN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDN.setText("Đăng nhập");
        btnDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDNActionPerformed(evt);
            }
        });
        getContentPane().add(btnDN);
        btnDN.setBounds(460, 440, 100, 25);

        btnDK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDK.setText("Đăng kí");
        btnDK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDKActionPerformed(evt);
            }
        });
        getContentPane().add(btnDK);
        btnDK.setBounds(710, 440, 100, 25);
        getContentPane().add(txtPassword);
        txtPassword.setBounds(610, 380, 200, 25);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/xoa.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(870, 40, 20, 20);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/arrow-92-24.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(0, 40, 30, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dangki1.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 900, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDNActionPerformed
        // TODO add your handling code here:
        DangNhapForm dn = new DangNhapForm();
        DangNhapForm.main(null);
    }//GEN-LAST:event_btnDNActionPerformed

    private void btnDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDKActionPerformed
        // TODO add your handling code here:
        int dk = JOptionPane.showConfirmDialog(this, "Bạn có muốn đăng kí","Thông báo", JOptionPane.YES_NO_OPTION);
        if(dk!= JOptionPane.YES_OPTION){
            return;
        }
        try{
            Connection con = new DBUtils().createConn();
            String SQL = "SELECT TenDN FROM KHACHHANG";
            Statement statement= con.createStatement();
            ResultSet rs=statement.executeQuery(SQL);
            while(rs.next()){
                if(txtUserName.getText().equals(rs.getString("TenDN")))
                {
                    JOptionPane.showMessageDialog(this, "Bị trùng tên đăng nhập, mời bạn nhập lại");
                }
            }
        } catch (SQLException ex) {
                ex.printStackTrace();
        }
        try{
            Connection con = new DBUtils().createConn();
            String sql = "insert into KHACHHANG (MAKH, TENKH, NGSINH, GIOITINH, EMAIL, SDT, TENDN, MK, TONGTIEN) VALUES (?, ?, ?, ?, ?, ?, ? ,?, 0)";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, LayMaKH());
            ps.setString(2, txtTenKH.getText());
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            ps.setString(3, df.format(dtcNgSinh.getDate()));
            if (cbbGT.getSelectedItem().toString().equals("Nữ") == true){
                ps.setBoolean(4, true);
            }
            else{
                ps.setBoolean(4, false);
            }
            ps.setString(5, txtEmail.getText());
            ps.setString(6, txtSDT.getText());
            ps.setString(7, txtUserName.getText());
            ps.setString(8, txtPassword.getText());
            int n = ps.executeUpdate();
            
            if(txtTenKH.getText().equals("")|dtcNgSinh.getDate().toString().equals("")|cbbGT.getSelectedItem().toString().equals("")|txtEmail.getText().equals("")|txtSDT.getText().equals("")|txtUserName.getText().equals("")|txtPassword.getText().equals(""))
            {
                JOptionPane.showMessageDialog(this, "Không để thông tin trống");
            }
            else if(n!=0){
                JOptionPane.showMessageDialog(this, "Đăng kí thành công");
                CustomerPage cp = new CustomerPage(txtUserName.getText());
            }
        
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnDKActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        mainpage.main(null);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangKi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDK;
    private javax.swing.JButton btnDN;
    private javax.swing.JComboBox<String> cbbGT;
    private com.toedter.calendar.JDateChooser dtcNgSinh;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
